### ISSUE TITLE
A question about the implementation in pytorch

### ISSUE THREAD

**Issue by Tangzy7** [delijati/pytorch-siamese#4]
Hi, the way you implement siamese network is like that:

```
output1,output2 = model(x0, x1)
loss = criterion (output1,output2)
```

And here is the another way:

```
output1 = model.forward_once(x0)
output2 = model.forward_once(x1)
loss = criterion (output1,output2)
```

Are they different?

**Comment by delijati** [comment]
It's the same, if you call `model(x0, x1)` it will call [`forward`](https://github.com/delijati/pytorch-siamese/blob/master/net.py#L26) and there you see the `forward_once` calls.
